Blogger.Web/Models/Domain/BlogPost.cs
namespace Blogger.Web.Models.Domain
{
    public class BlogPost
    {
        public Guid Id { get; set; }

        public string Heading { get; set; }

        public string PageTitle { get; set; }

        public string Content { get; set; }

        public string ShortDescription { get; set; }
         
        public string FeaturedImageUrl { get; set; }

        public string UrlHandle { get; set; }

        public DateTime PublishedDate { get; set; }

        public string Author { get; set; }
         
        public bool Visible { get; set; }

        public ICollection<Tag> Tags { get; set; }
    }
}

Blogger.Web/Models/Domain/Tag.cs
namespace Blogger.Web.Models.Domain
{
    public class Tag
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }
        public string? DisplayName { get; set; }

        public ICollection<BlogPost>? BlogPosts { get; set; }
    }
}

Blogger.Web/Models/ErrorViewModel.cs
namespace Blogger.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Blogger.Web/Models/ViewModels/AddBlogRequest.cs
using Blogger.Web.Models.Domain;

namespace Blogger.Web.Models.ViewModels
{
    public class AddBlogRequest
    {
        public string Heading { get; set; }

        public string PageTitle { get; set; }

        public string Content { get; set; }

        public string ShortDescription { get; set; }

        public string FeaturedImageUrl { get; set; }

        public string UrlHandle { get; set; }

        public DateTime PublishedDate { get; set; }

        public string Author { get; set; }

        public bool Visible { get; set; }

        public ICollection<Tag> Tags { get; set; }
    }
}

Blogger.Web/Models/ViewModels/AddTagRequest.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Blogger.Web.Models.ViewModels
{
    public class AddTagRequest
    {
        public string Name { get; set; }
        public string DisplayName { get; set; }
    }
}

Blogger.Web/Models/ViewModels/EditTagRequest.cs
namespace Blogger.Web.Models.ViewModels
{
    public class EditTagRequest
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }
        public string? DisplayName { get; set; }
    }
}

Blogger.Web/Controllers/AdminTagsController.cs
using Blogger.Web.Data;
using Blogger.Web.Models.Domain;
using Blogger.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blogger.Web.Controllers
{
    public class AdminTagsController : Controller
    {
        private BloggerDbContext _bloggerDbContext;

        public AdminTagsController(BloggerDbContext bloggerDbContext)
        {
            _bloggerDbContext = bloggerDbContext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {
            var newTag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName
            };

            await _bloggerDbContext.Tags.AddAsync(newTag);
            await _bloggerDbContext.SaveChangesAsync();

            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var List = await _bloggerDbContext.Tags.ToListAsync();

            return View(List);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var tag = await _bloggerDbContext.Tags.SingleOrDefaultAsync(x => x.Id == id);

            if(tag != null)
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName
                };

                return View(editTagRequest);
            }

            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName
            };

            var existingTag = await _bloggerDbContext.Tags.FindAsync(tag.Id);

            if(existingTag != null)
            {
                existingTag.Name = tag.Name;
                existingTag.DisplayName = tag.DisplayName;

                await _bloggerDbContext.SaveChangesAsync();
                return RedirectToAction("List");

            }

            return View("Edit" , new {id = tag.Id } );
        }
        
        public async Task<IActionResult> DeleteTag(Guid id)
        {
            var tag = await _bloggerDbContext.Tags.FindAsync(id);

            if(tag != null)
            {
                _bloggerDbContext.Tags.Remove(tag);
                await _bloggerDbContext.SaveChangesAsync();
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {
            var tag = await _bloggerDbContext.Tags.FindAsync(editTagRequest.Id);

            if(tag != null )
            {
                _bloggerDbContext.Tags.Remove(tag);
                await _bloggerDbContext.SaveChangesAsync();
            }

            return RedirectToAction("List");
        }

    }
}

Blogger.Web/Controllers/HomeController.cs
using Blogger.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Blogger.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Blogger.Web/Views/AdminTags/Add.cshtml
@model Blogger.Web.Models.ViewModels.AddTagRequest;

@{
}
<h1>Add New Tag - Admin Functionality</h1>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" class="form-control" id="name" asp-for="Name">
        </div>
        <div class="mb-3">
            <label class="form-label">Display Name</label>
            <input type="text" class="form-control" id="displayName" asp-for="DisplayName">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Blogger.Web/Views/AdminTags/AddBlog.cshtml
@model Blogger.Web.Models.ViewModels.AddBlogRequest;

@{
}
<h1>Add New Blog - Admin Functionality</h1>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Heading</label>
            <input type="text" class="form-control" id="heading" asp-for="Heading">
            <div class="mb-3">
                <label class="form-label">PageTitle</label>
                <input type="text" class="form-control" id="pageTitle" asp-for="PageTitle">
            </div>
            <div class="mb-3">
                <label class="form-label">Content</label>
                <input type="text" class="form-control" id="content" asp-for="Content">
            </div>
            <div class="mb-3">
                <label class="form-label">ShortDescription</label>
                <input type="text" class="form-control" id="description" asp-for="ShortDescription">
            </div>
            <div class="mb-3">
                <label class="form-label">FeaturedImageUrl</label>
                <input type="text" class="form-control" id="image-url" asp-for="FeaturedImageUrl">
            </div>
            <div class="mb-3">
                <label class="form-label">UrlHandle</label>
                <input type="text" class="form-control" id="url-handle" asp-for="UrlHandle">
            </div>
            <div class="mb-3">
                <label class="form-label">Author</label>
                <input type="text" class="form-control" id="author" asp-for="Author">
            </div>
        </div>
        <div class="mb-3">
            <label class="form-label">Tags</label>
            <input type="text" class="form-control" id="tags" asp-for="Tags">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Blogger.Web/Views/AdminTags/Edit.cshtml
@model Blogger.Web.Models.ViewModels.EditTagRequest;
@{
}

<h1>Edit your Tag details here</h1>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Id</label>
            <input type="text" class="form-control" id="name" asp-for="Id" readonly>
        </div>
        <div class="mb-3">
            <label class="form-label">Edit Name</label>
            <input type="text" class="form-control" id="name" asp-for="Name">
        </div>
        <div class="mb-3">
            <label class="form-label">Edit Display Name</label>
            <input type="text" class="form-control" id="displayName" asp-for="DisplayName">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="submit" class="btn btn-primary" asp-area="" asp-controller="AdminTags" asp-action="Delete">Delete</button>
    </form>
</div>

Blogger.Web/Views/AdminTags/List.cshtml
@model List<Blogger.Web.Models.Domain.Tag>

@{
}
<div class="container">
    @if (Model != null)
    {
        <table class="table">
            <thead>
                <tr>
                    <th> Id </th>
                    <th> Name </th>
                    <th> Display Name </th>
                    <th>  </th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var tag in Model)
                {
                    <tr>
                        <td> @tag.Id </td>
                        <td> @tag.Name </td>
                        <td> @tag.DisplayName </td>
                        <td> <a asp-area="" asp-controller="AdminTags" asp-action="Edit" asp-route-Id="@tag.Id" >Edit</a></td>
                        <td> <a asp-area="" asp-controller="AdminTags" asp-action="DeleteTag" asp-route-Id="@tag.Id">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

Blogger.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Blogger.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blogger.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Blogger.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blogger.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <button class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </button>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="Add">Admin Tags</a></li>
                                <li><a class="dropdown-item" asp-controller="AdminTags" asp-action="List">Show All Tags</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Blogger.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>